# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech blog by Audun Solemdal
email: audun@solom.no
description: > # this means to ignore newlines until "baseurl:"
  Blog posts on Azure, DevOps, Kubernetes and Cloud native
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://solom.no" # the base hostname & protocol for your site
twitter_username: ASolemdal
github_username: audunsolemdal
permalink: /:year/:month/:title.html
excerpt_separator: "<!--more-->" # Use excerpts on front page

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
